financial_controlling:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('FINANCIAL_DB_HOST', 'localhost') }}"
      port: "{{ env_var('FINANCIAL_DB_PORT', '5432') | int }}"
      user: "{{ env_var('FINANCIAL_DB_USER', 'financial_admin') }}"
      password: "{{ env_var('FINANCIAL_DB_PASSWORD', 'fin_controlling_2024') }}"
      dbname: "{{ env_var('FINANCIAL_DB_NAME', 'financial_controlling') }}"
      schema: public
      threads: 4
